apply plugin: 'java'

repositories {
    maven {
        url = uri("https://artifactory.production.cloud.oxoe.io/artifactory/libs-release")
    }
}

configurations {
    toCopy
}

dependencies {
    toCopy 'org.wiremock:wiremock:3.12.0'
    testImplementation(testFixtures(project(":com.openexchange.core-test")))
}

task download(type: Copy) {
    from configurations.toCopy 
    into 'lib'
}

//test {
//    testLogging.showStandardStreams = true
//}
