# URL of the Matrix server
#
com.openexchange.matrixproxy.servlet.serverUrl=https://matrix.dpx-wp7a.at-univention.de

# URL of the Bot Server
#
com.openexchange.matrixproxy.servlet.botURL=https://meetings-widget-api.dpx-wp7a.at-univention.de

# Application Service Token to login to Matrix server
#
com.openexchange.matrixproxy.servlet.asToken=

# Comma separated list of path to pass-through to the Bot server
# Every path that doesn't start with any of them listed here will be
# rejected.
com.openexchange.matrixproxy.servlet.apiWhitelist=/v1/meeting,/v1/health
