# Category identifier for OX App Suite
io.ox.public-sector//navigation/oxtabname=tab_groupware

# URL of the InterCom Service.
# Defaults to the same host as the OX App Suite UI.
io.ox.public-sector//ics/url=

# Remove quick launchers
io.ox/core//apps/quickLaunchCount=0

# Set Phoenix theme
io.ox/core//theme=phoenix
