# URL of the configuration for the Central Navigation service.
# If empty, the native OX App Suite launcher will be displayed
io.ox.public-sector//navigation/url=

# Category identifier for OX App Suite
io.ox.public-sector//navigation/oxcategory=tab_groupware

# Remove quick launchers
io.ox/core//apps/quickLaunchCount=0

# Set Phoenix theme
io.ox/core//theme=phoenix
