# URL of the configuration for the Central Navigation service.
# If empty, the native OX App Suite launcher will be displayed
io.ox.public-sector//navigation/url=

# Category identifier for OX App Suite
io.ox.public-sector//navigation/oxcategory=tab_groupware

# URL of the InterCom Service.
# Defaults to the same host as the OX App Suite UI.
io.ox.public-sector//ics/url=

# Remove quick launchers
io.ox/core//apps/quickLaunchCount=0

# Set Phoenix theme
io.ox/core//theme=phoenix
